## Preprocessing

In [6]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd 
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [7]:
# Drop the non-beneficial ID columns, 'EIN'

application_df = application_df.drop(columns=['EIN','NAME'], axis=1)
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [8]:
# Determine the number of unique values in each column.
for i in application_df.columns:
    print(i, len(application_df[i].unique()))

APPLICATION_TYPE 17
AFFILIATION 6
CLASSIFICATION 71
USE_CASE 5
ORGANIZATION 4
STATUS 2
INCOME_AMT 9
SPECIAL_CONSIDERATIONS 2
ASK_AMT 8747
IS_SUCCESSFUL 2

In [9]:
# Look at APPLICATION_TYPE value counts for binning
app_counts = application_df['APPLICATION_TYPE'].value_counts()
app_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [10]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_counts[app_counts<1000].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
Other     2266
T4        1542
T6        1216
T5        1173
T19       1065
Name: count, dtype: int64

In [11]:
# Look at CLASSIFICATION value counts for binning
classification_counts = application_df['CLASSIFICATION'].value_counts()

In [12]:
# You may find it helpful to look at CLASSIFICATION value counts >1
application_df['CLASSIFICATION'].value_counts().loc[lambda x : x >1]

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [13]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification_counts[classification_counts<1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")
    
# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: count, dtype: int64

In [14]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies = pd.get_dummies(application_df)
application_dummies.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,AFFILIATION_CompanySponsored,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,True,False,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,True,False,True,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,True,False,False,False,True,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [15]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop('IS_SUCCESSFUL', axis=1).values
y = application_dummies['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [16]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [17]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = X_train_scaled.shape[1]

hidden_node1 = 9
hidden_node2 = 3
# Add a third hidden layer
hidden_node3 = 1


nn_model_1 = tf.keras.models.Sequential()

# First hidden layer
nn_model_1.add(tf.keras.layers.Dense(units=hidden_node1, activation='relu', input_dim=input_features))

# Second hidden layer
nn_model_1.add(tf.keras.layers.Dense(units=hidden_node2, activation='relu'))

# Third hidden layer
nn_model_1.add(tf.keras.layers.Dense(units=hidden_node3, activation='relu'))


# Output layer (output is 1 and sigmoid because it's binary classifier)
nn_model_1.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn_model_1.summary()

WARNING:tensorflow:From C:\Users\swati\anaconda3\Lib\site-packages\keras\src\backend.py:873: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 9)                 369

 dense_1 (Dense)             (None, 3)                 30

 dense_2 (Dense)             (None, 1)                 4

 dense_3 (Dense)             (None, 1)                 2

=================================================================
Total params: 405 (1.58 KB)
Trainable params: 405 (1.58 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [18]:
# Compile the model
nn_model_1.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

WARNING:tensorflow:From C:\Users\swati\anaconda3\Lib\site-packages\keras\src\optimizers\__init__.py:309: The name tf.train.Optimizer is deprecated. Please use tf.compat.v1.train.Optimizer instead.

In [19]:
# Create a callback that saves the model's weights every five epochs
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define checkpoints variables
os.makedirs('checkpoints/', exist_ok=True)
checkpoint_path= 'checkpoints/weights.{epoch}.hdf5'

# Create callback 
cp_callback = ModelCheckpoint(filepath=checkpoint_path,
                              verbose=1,
                              save_weights_only=True,
                              save_freq='epoch',
                              period=5)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [20]:
# Train the model
fit_model = nn_model_1.fit(X_train_scaled, y_train, epochs=100,callbacks=[cp_callback])

Epoch 1/100
WARNING:tensorflow:From C:\Users\swati\anaconda3\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From C:\Users\swati\anaconda3\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

804/804 [==============================] - 2s 1ms/step - loss: 0.6297 - accuracy: 0.6844
Epoch 2/100
804/804 [==============================] - 1s 992us/step - loss: 0.5811 - accuracy: 0.7199
Epoch 3/100
804/804 [==============================] - 1s 921us/step - loss: 0.5714 - accuracy: 0.7226
Epoch 4/100
804/804 [==============================] - 1s 919us/step - loss: 0.5685 - accuracy: 0.7240
Epoch 5/100
791/804 [============================>.] - ETA: 0s - loss: 0.5670 - accuracy: 0.7244
Epoch 5: saving model to checkpoints\weights.5.hdf5
804/804 [==============================] - 1s 916us/step - loss: 0.5673 - accuracy: 0.7242
Epoch 6/100
804/804 [==============================] - 1s 923us/step - loss: 0.5665 - accuracy: 0.7247
Epoch 7/100
804/804 [==============================] - 1s 907us/step - loss: 0.5658 - accuracy: 0.7255
Epoch 8/100
804/804 [==============================] - 1s 980us/step - loss: 0.5641 - accuracy: 0.7255
Epoch 9/100
804/804 [==============================] - 1s 991us/step - loss: 0.5629 - accuracy: 0.7273
Epoch 10/100
796/804 [============================>.] - ETA: 0s - loss: 0.5629 - accuracy: 0.7268
Epoch 10: saving model to checkpoints\weights.10.hdf5
804/804 [==============================] - 1s 968us/step - loss: 0.5623 - accuracy: 0.7275
Epoch 11/100
804/804 [==============================] - 1s 940us/step - loss: 0.5613 - accuracy: 0.7294
Epoch 12/100
804/804 [==============================] - 1s 969us/step - loss: 0.5601 - accuracy: 0.7308
Epoch 13/100
804/804 [==============================] - 1s 977us/step - loss: 0.5596 - accuracy: 0.7311
Epoch 14/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5594 - accuracy: 0.7316
Epoch 15/100
797/804 [============================>.] - ETA: 0s - loss: 0.5588 - accuracy: 0.7319
Epoch 15: saving model to checkpoints\weights.15.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5590 - accuracy: 0.7317
Epoch 16/100
804/804 [==============================] - 1s 945us/step - loss: 0.5587 - accuracy: 0.7315
Epoch 17/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5587 - accuracy: 0.7313
Epoch 18/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5586 - accuracy: 0.7318
Epoch 19/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5581 - accuracy: 0.7321
Epoch 20/100
791/804 [============================>.] - ETA: 0s - loss: 0.5584 - accuracy: 0.7316
Epoch 20: saving model to checkpoints\weights.20.hdf5
804/804 [==============================] - 1s 971us/step - loss: 0.5585 - accuracy: 0.7316
Epoch 21/100
804/804 [==============================] - 1s 979us/step - loss: 0.5582 - accuracy: 0.7317
Epoch 22/100
804/804 [==============================] - 1s 918us/step - loss: 0.5582 - accuracy: 0.7320
Epoch 23/100
804/804 [==============================] - 1s 958us/step - loss: 0.5581 - accuracy: 0.7321
Epoch 24/100
804/804 [==============================] - 1s 974us/step - loss: 0.5579 - accuracy: 0.7322
Epoch 25/100
789/804 [============================>.] - ETA: 0s - loss: 0.5578 - accuracy: 0.7332
Epoch 25: saving model to checkpoints\weights.25.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5578 - accuracy: 0.7330
Epoch 26/100
804/804 [==============================] - 1s 913us/step - loss: 0.5574 - accuracy: 0.7334
Epoch 27/100
804/804 [==============================] - 1s 900us/step - loss: 0.5575 - accuracy: 0.7327
Epoch 28/100
804/804 [==============================] - 1s 963us/step - loss: 0.5573 - accuracy: 0.7334
Epoch 29/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5573 - accuracy: 0.7334
Epoch 30/100
802/804 [============================>.] - ETA: 0s - loss: 0.5573 - accuracy: 0.7328
Epoch 30: saving model to checkpoints\weights.30.hdf5
804/804 [==============================] - 1s 960us/step - loss: 0.5573 - accuracy: 0.7327
Epoch 31/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5574 - accuracy: 0.7332
Epoch 32/100
804/804 [==============================] - 1s 985us/step - loss: 0.5571 - accuracy: 0.7329
Epoch 33/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7328
Epoch 34/100
804/804 [==============================] - 1s 945us/step - loss: 0.5572 - accuracy: 0.7332
Epoch 35/100
780/804 [============================>.] - ETA: 0s - loss: 0.5568 - accuracy: 0.7331
Epoch 35: saving model to checkpoints\weights.35.hdf5
804/804 [==============================] - 1s 990us/step - loss: 0.5569 - accuracy: 0.7329
Epoch 36/100
804/804 [==============================] - 1s 956us/step - loss: 0.5567 - accuracy: 0.7332
Epoch 37/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5568 - accuracy: 0.7334
Epoch 38/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5567 - accuracy: 0.7333
Epoch 39/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5569 - accuracy: 0.7339
Epoch 40/100
779/804 [============================>.] - ETA: 0s - loss: 0.5571 - accuracy: 0.7325
Epoch 40: saving model to checkpoints\weights.40.hdf5
804/804 [==============================] - 1s 992us/step - loss: 0.5566 - accuracy: 0.7327
Epoch 41/100
804/804 [==============================] - 1s 980us/step - loss: 0.5564 - accuracy: 0.7333
Epoch 42/100
804/804 [==============================] - 1s 964us/step - loss: 0.5563 - accuracy: 0.7339
Epoch 43/100
804/804 [==============================] - 1s 993us/step - loss: 0.5564 - accuracy: 0.7328
Epoch 44/100
804/804 [==============================] - 1s 991us/step - loss: 0.5562 - accuracy: 0.7340
Epoch 45/100
751/804 [===========================>..] - ETA: 0s - loss: 0.5561 - accuracy: 0.7347
Epoch 45: saving model to checkpoints\weights.45.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5563 - accuracy: 0.7345
Epoch 46/100
804/804 [==============================] - 1s 962us/step - loss: 0.5564 - accuracy: 0.7329
Epoch 47/100
804/804 [==============================] - 1s 965us/step - loss: 0.5561 - accuracy: 0.7340
Epoch 48/100
804/804 [==============================] - 1s 960us/step - loss: 0.5561 - accuracy: 0.7337
Epoch 49/100
804/804 [==============================] - 1s 922us/step - loss: 0.5560 - accuracy: 0.7336
Epoch 50/100
768/804 [===========================>..] - ETA: 0s - loss: 0.5564 - accuracy: 0.7339
Epoch 50: saving model to checkpoints\weights.50.hdf5
804/804 [==============================] - 1s 936us/step - loss: 0.5562 - accuracy: 0.7340
Epoch 51/100
804/804 [==============================] - 1s 933us/step - loss: 0.5560 - accuracy: 0.7324
Epoch 52/100
804/804 [==============================] - 1s 989us/step - loss: 0.5561 - accuracy: 0.7342
Epoch 53/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5560 - accuracy: 0.7338
Epoch 54/100
804/804 [==============================] - 1s 939us/step - loss: 0.5558 - accuracy: 0.7328
Epoch 55/100
784/804 [============================>.] - ETA: 0s - loss: 0.5557 - accuracy: 0.7337
Epoch 55: saving model to checkpoints\weights.55.hdf5
804/804 [==============================] - 1s 990us/step - loss: 0.5559 - accuracy: 0.7334
Epoch 56/100
804/804 [==============================] - 1s 996us/step - loss: 0.5557 - accuracy: 0.7334
Epoch 57/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5557 - accuracy: 0.7327
Epoch 58/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7342
Epoch 59/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5556 - accuracy: 0.7329
Epoch 60/100
772/804 [===========================>..] - ETA: 0s - loss: 0.5555 - accuracy: 0.7345
Epoch 60: saving model to checkpoints\weights.60.hdf5

804/804 [==============================] - 1s 1ms/step - loss: 0.5555 - accuracy: 0.7340
Epoch 61/100
804/804 [==============================] - 1s 982us/step - loss: 0.5554 - accuracy: 0.7337
Epoch 62/100
804/804 [==============================] - 1s 930us/step - loss: 0.5556 - accuracy: 0.7336
Epoch 63/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5554 - accuracy: 0.7337
Epoch 64/100
804/804 [==============================] - 1s 979us/step - loss: 0.5556 - accuracy: 0.7344
Epoch 65/100
791/804 [============================>.] - ETA: 0s - loss: 0.5548 - accuracy: 0.7332
Epoch 65: saving model to checkpoints\weights.65.hdf5
804/804 [==============================] - 1s 979us/step - loss: 0.5550 - accuracy: 0.7333
Epoch 66/100
804/804 [==============================] - 1s 945us/step - loss: 0.5555 - accuracy: 0.7329
Epoch 67/100
804/804 [==============================] - 1s 978us/step - loss: 0.5552 - accuracy: 0.7341
Epoch 68/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5552 - accuracy: 0.7337
Epoch 69/100
804/804 [==============================] - 1s 951us/step - loss: 0.5552 - accuracy: 0.7343
Epoch 70/100
795/804 [============================>.] - ETA: 0s - loss: 0.5555 - accuracy: 0.7339
Epoch 70: saving model to checkpoints\weights.70.hdf5
804/804 [==============================] - 1s 966us/step - loss: 0.5553 - accuracy: 0.7341
Epoch 71/100
804/804 [==============================] - 1s 910us/step - loss: 0.5551 - accuracy: 0.7343
Epoch 72/100
804/804 [==============================] - 1s 948us/step - loss: 0.5552 - accuracy: 0.7339
Epoch 73/100
804/804 [==============================] - 1s 975us/step - loss: 0.5551 - accuracy: 0.7347
Epoch 74/100
804/804 [==============================] - 1s 929us/step - loss: 0.5549 - accuracy: 0.7343
Epoch 75/100
760/804 [===========================>..] - ETA: 0s - loss: 0.5553 - accuracy: 0.7334
Epoch 75: saving model to checkpoints\weights.75.hdf5
804/804 [==============================] - 1s 950us/step - loss: 0.5551 - accuracy: 0.7337
Epoch 76/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5549 - accuracy: 0.7344
Epoch 77/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5548 - accuracy: 0.7341
Epoch 78/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5550 - accuracy: 0.7334
Epoch 79/100
804/804 [==============================] - 1s 935us/step - loss: 0.5549 - accuracy: 0.7334
Epoch 80/100
752/804 [===========================>..] - ETA: 0s - loss: 0.5541 - accuracy: 0.7345
Epoch 80: saving model to checkpoints\weights.80.hdf5
804/804 [==============================] - 1s 955us/step - loss: 0.5550 - accuracy: 0.7343
Epoch 81/100
804/804 [==============================] - 1s 989us/step - loss: 0.5545 - accuracy: 0.7344
Epoch 82/100
804/804 [==============================] - 1s 943us/step - loss: 0.5546 - accuracy: 0.7339
Epoch 83/100
804/804 [==============================] - 1s 907us/step - loss: 0.5547 - accuracy: 0.7341
Epoch 84/100
804/804 [==============================] - 1s 957us/step - loss: 0.5545 - accuracy: 0.7345
Epoch 85/100
778/804 [============================>.] - ETA: 0s - loss: 0.5549 - accuracy: 0.7344
Epoch 85: saving model to checkpoints\weights.85.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5547 - accuracy: 0.7345
Epoch 86/100
804/804 [==============================] - 1s 908us/step - loss: 0.5545 - accuracy: 0.7339
Epoch 87/100
804/804 [==============================] - 1s 909us/step - loss: 0.5544 - accuracy: 0.7345
Epoch 88/100
804/804 [==============================] - 1s 915us/step - loss: 0.5546 - accuracy: 0.7343
Epoch 89/100
804/804 [==============================] - 1s 931us/step - loss: 0.5545 - accuracy: 0.7350
Epoch 90/100
779/804 [============================>.] - ETA: 0s - loss: 0.5536 - accuracy: 0.7351
Epoch 90: saving model to checkpoints\weights.90.hdf5
804/804 [==============================] - 1s 936us/step - loss: 0.5543 - accuracy: 0.7345
Epoch 91/100
804/804 [==============================] - 1s 902us/step - loss: 0.5545 - accuracy: 0.7345
Epoch 92/100
804/804 [==============================] - 1s 928us/step - loss: 0.5543 - accuracy: 0.7350
Epoch 93/100
804/804 [==============================] - 1s 929us/step - loss: 0.5546 - accuracy: 0.7341
Epoch 94/100
804/804 [==============================] - 1s 974us/step - loss: 0.5544 - accuracy: 0.7334
Epoch 95/100
798/804 [============================>.] - ETA: 0s - loss: 0.5545 - accuracy: 0.7336
Epoch 95: saving model to checkpoints\weights.95.hdf5
804/804 [==============================] - 1s 975us/step - loss: 0.5545 - accuracy: 0.7336
Epoch 96/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5543 - accuracy: 0.7349
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5544 - accuracy: 0.7337
Epoch 98/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5539 - accuracy: 0.7345
Epoch 99/100
804/804 [==============================] - 1s 1ms/step - loss: 0.5546 - accuracy: 0.7339
Epoch 100/100
771/804 [===========================>..] - ETA: 0s - loss: 0.5549 - accuracy: 0.7330
Epoch 100: saving model to checkpoints\weights.100.hdf5
804/804 [==============================] - 1s 1ms/step - loss: 0.5540 - accuracy: 0.7338

In [21]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model_1.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5652 - accuracy: 0.7290 - 283ms/epoch - 1ms/step
Loss: 0.5651555061340332, Accuracy: 0.7289795875549316

In [22]:
# Export our model to HDF5 file
nn_model_1.save("C:/downloads/AlphabetSoupCharity_model_optimise2.h5")

C:\Users\swati\anaconda3\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(